[build]
  command = "cd vite && npm run build && cd .. && npm run build && node -e \"require('fs').copyFileSync('dist/_redirects', 'vite/dist/_redirects')\""
  publish = "vite/dist"

[functions]
  included_files = ["src/db/schema.ts"]
  directory = ".netlify/functions-internal"
